version: '3.7'

services:
  database:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - ./database/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=portal_user
      - MYSQL_DATABASE=portal_db
    restart: always
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048M
